name: React CI/CD Pipeline

on:
  push:
    branches:
      - new_branch

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build the app
        env:
          SKIP_PREFLIGHT_CHECK: true
        run: |
          unset CI
          npm run build

      - name: Deploy to EC2
        env:
          EC2_PUBLIC_IP: '3.96.177.98'      # Hardcoded IP Address
          EC2_USER: 'ec2-user'              # Hardcoded username
          EC2_SSH_KEY: 'MIIEowIBAAKCAQEAv5Pq2HGx09vafcyufuylkRjyhTHpVtyiWBpMBqNiPWGcJMcKDGooZ6gRV1tz9mz5Oruf3LjfadSiWwdI2WyCRzNfWZKW4EBH2UUKiWmrcAOcJVP3n+5j0UwWqBImMtLGKkHyY5YwCqnU/jy/zarlqUwM187DdB2844mHhRwWc8HFnPuYqml84J0LZ/3Ei2nc7af1+jmu+PhqsmO7b2u3qYbtHUujKEB8iTzfhova1bhPvJI6WeZu37K8Ixohmz937/6jDve4uc68xrQrto5AVlYO2a09bbsM1R7xF8h4V0ms/hXeSN7SKBffGbSsGPlnHtvRLYo9SsyI21295YNgiwIDAQABAoIBABL1uqpNJkJHYepNVX+uP/yKMYZJGETGdTKu95M4nEJi5KcnI7Fy2CjaE01H+cQLqObNJtcbXNEGgELuB6GtAX+2b9tXjKMI+ZNhJ9fNo2/ki5GOK9WiLDLMivl7QliJT59jA3AjrwF/KVs3++uI3E3S/vpktidJwiXquITN8NLn0JRO0mGn4xb5cBpxI32ctwN8GU+qtsU7B/zPnPs2v3GAJuIMc/bSQRhMrbHIDhRydFlJYWSaDwfo8rPTmmO5pOWjJf29JmVswuH6dXj6vj+0A8iduq67tQSXgA3k7KadEyOavTMo6I3lnxt7wdzm4Rr0b7Kt+N9fik+j3PjaIAECgYEA6q3tXaP847/Y4363WkIIj9BLGqoHoyyy1Y4FxrD5luts1uRU7kSPRs66QrQMfDNwGGipehBJl5muFjmPKWZ8ZWHT5xlhNREp42SUKeHaFT4s8Wk3G1ORNTdyHesjUH18D1AVlv+jJR/M4EqX5RbapH6zyxx82tnUZNstwp5EeAECgYEA0PuNN3Q31lnRiHVsEmXKRAdfqsZd1xGWmuktp0WZur5Gl+lrTKOp82XRPH+K0kKWLTvX6QVaEqMWn0A0wmVjIwDI8XHzf9jUhC28P+Y4Q6B6cVOq+KQOEMGSbwY99eaF8uhDWFdHr5sIucXDcaYgau4+z7ZdNbVksc7X8KwWOIsCgYBKihPqujuI21a4a3cxY+f0ReSVA4yJd5kV25ZaFbwxA3X+i2euhng7tU3UAfw1NuFT32p1Ktc1H8r7pCykqbi5OuljbdxCTsFPSJMG+oWaWbVMuG6Yb2Kf1IyalCUTW8gb1QQGggv/rqoUU50LVsb7mILi8Jl3qdiccEGIn1yAAQKBgDC7F7jgnsya8SMyzlqT5dBrL8Gws90cutOwn/arYieLiwaNZXnfiBe7nEjRLNvOrxopJDWwC8rgwLutyx+xaKaW3kR+39rmAtg3mfgEhQYv+51Fd063YphBqxW8jOI0OPPleR62a37lVemL1gFATbrhh0AENEP74lkb9Hqohh31AoGBAJRE2S/+PuWzioZZ/+9pGkbeqsF6w107NA9uBTkuyB4DY2UoDuuSY5luMfEn8KNHLuwBAIcgfkakLrv5Tyuz+A+dongclq/Alv9gUokeYmx87G5UB0aYqGPSOj4pabPZvYisXTpK71aKjO5Z+FaA/dMmTRXfEd6AUKKoCch/Nl36'  # Hardcoded SSH Key (Not Recommended)
        run: |
          echo "${EC2_SSH_KEY}" > ssh_key
          chmod 600 ssh_key
          ssh -i ssh_key ${EC2_USER}@${EC2_PUBLIC_IP} "sudo mkdir -p /var/www/html/splitwise"
          scp -i ssh_key -r build/* ${EC2_USER}@${EC2_PUBLIC_IP}:/var/www/html/splitwise/
          ssh -i ssh_key ${EC2_USER}@${EC2_PUBLIC_IP} "sudo systemctl restart nginx"
