name: React CI/CD Pipeline

on:
  push:
    branches:
      - new_branch

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build the app
        env:
          SKIP_PREFLIGHT_CHECK: true
        run: |
          unset CI
          npm run build

      - name: Add EC2 Host Key to Known Hosts
        run: |
          mkdir -p ~/.ssh  # Create the SSH directory if it doesn't exist
          ssh-keyscan -H 35.183.97.89 >> ~/.ssh/known_hosts  # Add EC2's public IP to known hosts

      - name: Deploy to EC2
        env:
            EC2_PUBLIC_IP: '35.183.97.89'      # Hardcoded IP Address
            EC2_USER: 'ec2-user'              # Hardcoded username
            EC2_SSH_KEY: |
              -----BEGIN RSA PRIVATE KEY-----
              MIIEowIBAAKCAQEAvp83wqLf6eyy7T97AmSsAQoluFSJ2OiGqfFimc8TAza1Iuvfu1+gb72X5L9CFlYI93ODuiHODSRHIw8uOdiP0wm4asGwgifmot2jgbMYhoyQFAgCd7h47NBO0iYbtEq4Deod7n9agZQxRHfUKVIspUdKxupi6jAFnKlFkuaKlOzXBuJBi7u6iY53uJ8xYm8Wm3FtAg2IWQ0/6Z3YF5X7AMS3ia4IqjfeBJ5NQCW76sLsrT30JkyGI4EZuqWvzpYbqLtHD91WbN5EHTPGO48Cp0VcehU5SA+6f0Bb8B3CN/wfHn7/JPZ1lCRA+K55W15QTcgxM9BvemBf+lSdww62SwIDAQABAoIBADGqJAoHC5XUAM5FctQtzI68yRUcmYm1E5jldk4ioI5+y3Tcxb747EEQwalsl1hgdBecth5hvmC4KfydcOrLXLWcW7sc2dMfeDzIyFf7hJFRwBwn9hShMIhqwY6JNUClEw01CTVhYwBNzwRKwDE/4rfxOi9XVAw2FNA7XhAnFsYz96Bt8lgJCiLT/7EP8JlzAbV6XmaqN728/PhsZJLFucKiokOVCRcHXTLcZ9sD219wkGCtYVd6Yevc3jRO2hxwxv0IxwPNYD8RSv1FzWk53DRJN+bsbUCBHHfrDFQGvOolCllGBtDeRR5+TrAMNBtvYv9oM4hMsgPvhhlA7X95f5ECgYEA5j+aEIxctR/Sy0wOxgea9wNo3rNEHncZfUdlq4Dkmjhak+Y04apsRuUK26s/2LWoqmKyJlzqFo+E6S1i1Qm7A/5GfWy+OLZjKVLPmxSMxFK1EKVFGyR+P5amJgXtLjUldyH936nEz+Kj7OZKJNZdyzIJ1UoXj4qbkZCWeQVzARkCgYEA0/ELAnm8VUBC5lMsDGZ72/CMjaHxH4UEQbDBwxUqqS1W498YOsYJYwFi+gI6mvffmGfQwUFBT5//Vkz8l7PLu8dOPaB6GxzIZ/MN9yRw4gxWa/GItHi4pDKwPwOldkRyd7w1zGS0IPOkgMZSGMOeefEhpDcUuuzaI+9EZEYKqwMCgYBUEZr2OdnLxF/aHN40DijV0ifjUH8pxIDJDl2f/kL50GO6Js7eKrS4Of758BAy1zlLZRf5C+no7OQxo4G3mYLwVVJ1j1PxLx8LwpHM5Pb04+H6vu15mJyEKURnE7jjK0KPuhiRJtKWuQDzia4+vwqmG5Idj50Eqy5cOvfGHmg8WQKBgQCWBzN79SDUWEEDOi0cOg/DiWx1dgVyAn8Y4T7IEdu5FldDx1EnibhrVTfzMlC6Em09PYAQzVimPORK+wRzftrhehxwk4DcYGuc6fkg0bL20TT8BGZ5GlvaH+eTM8mVBq7hA2Ix5bd8+/ufDMRgs1kjiQX/cN5D1BY3CdCoCszScQKBgGSIRFNavbFp8VJxm87Ybwl7DLSjyijmowDri3lkzXB/dFn3/LrlyEvFNAxtoKOt+VHIbJlBPwpO7Je0UsSJAoAXYOYivrMzM9wz243Y/g1mQvUGOcqjCQfySDOirCp6gepIEU4/xrE0jKaP7u0MknqsPFW37Shy1xKKkqZP6y8v
              -----END RSA PRIVATE KEY-----
        run: |
            echo "${EC2_SSH_KEY}" > ssh_key
            chmod 600 ssh_key
            ssh -i ssh_key ${EC2_USER}@${EC2_PUBLIC_IP} "sudo mkdir -p /var/www/html/splitwise"
            scp -i ssh_key -r build/* ${EC2_USER}@${EC2_PUBLIC_IP}:/var/www/html/splitwise/splitwise
            ssh -i ssh_key ${EC2_USER}@${EC2_PUBLIC_IP} "sudo systemctl restart nginx"
              
    