name: React CI/CD Pipeline

on:
  push:
    branches:
      - new_branch

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build the app
        env:
          SKIP_PREFLIGHT_CHECK: true
        run: |
          unset CI
          npm run build

      - name: Deploy to EC2
        env:
          EC2_PUBLIC_IP: '35.183.97.89'      # Hardcoded IP Address
          EC2_USER: 'ec2-user'              # Hardcoded username
          EC2_SSH_KEY: 'MIIEowIBAAKCAQEAvp83wqLf6eyy7T97AmSsAQoluFSJ2OiGqfFimc8TAza1Iuvfu1+gb72X5L9CFlYI93ODuiHODSRHIw8uOdiP0wm4asGwgifmot2jgbMYhoyQFAgCd7h47NBO0iYbtEq4Deod7n9agZQxRHfUKVIspUdKxupi6jAFnKlFkuaKlOzXBuJBi7u6iY53uJ8xYm8Wm3FtAg2IWQ0/6Z3YF5X7AMS3ia4IqjfeBJ5NQCW76sLsrT30JkyGI4EZuqWvzpYbqLtHD91WbN5EHTPGO48Cp0VcehU5SA+6f0Bb8B3CN/wfHn7/JPZ1lCRA+K55W15QTcgxM9BvemBf+lSdww62SwIDAQABAoIBADGqJAoHC5XUAM5FctQtzI68yRUcmYm1E5jldk4ioI5+y3Tcxb747EEQwalsl1hgdBecth5hvmC4KfydcOrLXLWcW7sc2'
        run: |
          echo "${EC2_SSH_KEY}" > ssh_key
          chmod 600 ssh_key
          ssh -i ssh_key ${EC2_USER}@${EC2_PUBLIC_IP} "sudo mkdir -p /var/www/html/splitwise"
          scp -i ssh_key -r build/* ${EC2_USER}@${EC2_PUBLIC_IP}:/var/www/html/splitwise/
          ssh -i ssh_key ${EC2_USER}@${EC2_PUBLIC_IP} "sudo systemctl restart nginx"
